import { create } from 'zustand'
import { persist } from 'zustand/middleware';

export const useStore = create(  persist(
    (set) => ({
      flowOpen:false,
      Flow:'',
      communityFlow:'',
      user: null,
      jobs: null,
      job: null,
      comments: null,
      applicants: null,
      applicant: null,
      courses:null,
      lessons:null,
      course:null,
      posts:null,
      post:null,
      loading: false,
      process: null,
      loginError: null,
      registerError: null,
      verifyError: null,
      error: '',
      selectUserError:null,
      login:false,
      token:'',
        minutes:9,
        seconds:59,
       codeTimeOut:false,

  setUser: (user) => set({ user }),
  setJobs: (jobs) => set({ jobs }),
  setJob: (job) => set({ job }),
  setComments: (comments) => set({ comments }),
  setApplicants: (applicants) => set({ applicants }),
  setApplicant: (applicant) => set({ applicant }),
  setCourses: (courses) => set({ courses }),
  setLessons: (lessons) => set({ lessons }),
  setCourse: (course) => set({ course }),
  setFlow: (Flow) => set({ Flow }),
  setCommunityFlow: (communityFlow) => set({ communityFlow }),
  setPosts: (posts) => set({ posts }),
  setPost: (post) => set({ post }),
  setProcess: (process) => set({ process }),
  setLoading: (loading) => set({ loading }),
  setLogin: (login) => set({ login }),
  setError: (error) => set({ error }),
  setLoginError: (loginError) => set({ loginError }),
  setRegisterError: (registerError) => set({ registerError }),
  setVerifyError: (verifyError) => set({ verifyError }),
  setSelectUserError: (selectUserError) => set({ selectUserError }),
  setToken: (token) => set({ token }),
  setMinutes: (minutes) => set({ minutes }),
  setSeconds: (seconds) => set({ seconds }),
  setCodeTimeOut: (codeTimeOut) => set({ codeTimeOut }),
    handleClose : () => set((state)=>({flowOpen:false})),
    handleOpen: () => set((state)=>({flowOpen:true})),
  //  setAlert : (value) => set((state)=>({alert:value})),
    }),
    {
      name: 'user', // اسم المفتاح في localStorage
    }
  ))
